on:
  push:
    branches:
      - main

name: Generate Plots

jobs:
  generate_plots:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo rm -rf rendered

      - uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          R -e 'install.packages("ggplot2")'
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("tidyr")'
          R -e 'install.packages("svglite")'

      - name: Run R srcipt
        run: |
          mkdir -p rendered
          R < plots/success_rate.R --no-save

      - name: Add changed files
        run: |
          git checkout -b results
          git add rendered
          git -c user.name=Bot -c user.email=dummy@example.com commit --message "Update plots"
          git push --set-upstream origin results --force